class Employee:
    # carsSold should be an integer, revenueGen can be an integer or float, jobTitle can only be either 'salesman' or 'manager', fullName is a string
    def __init__(self, carsSold, revenueGen, jobTitle, fullName):
        self.cars_sold = carsSold
        self.revenue_generated = revenueGen
        self.position = jobTitle
        self.name = fullName

    # positionName can only be either 'salesman' or 'manager'
    def set_position(self,positionName):
        self.position = positionName

    # This function/method returns the position of the employee which is a string
    def get_position(self):
        return self.position
    
    # This function/method will increment the cars_sold of the employee object
    def increment_cars_sold(self):
        self.cars_sold += 1

    # This function/method will return the number of cars sold by the employee which is an integer
    def get_cars_sold(self):
        return self.cars_sold
    
    # This function/method will add amount to the existing revenue_generated by the employee object. Amount should be an integer or float
    def generate_revenue(self, amount):
        self.revenue_generated += amount
    
    # This function/method will return the amount of revenue generated by the employee which is an integer or float
    def get_revenue_generated(self):
        return self.revenue_generated
    